### ISSUE TITLE
Harmony should remove digits if every question starts with a digit

### ISSUE THREAD

**Issue by woodthom2** [harmonydata/harmony#23]
## Description

If I upload a CSV file like this, Harmony puts digits at the start of each question

```
1 I feel nervous
2 I feel afraid
```
## Environment

Web Harmony

## How to Reproduce

Make file `harmony.csv` with content
```
1 I feel nervous
2 I feel afraid
```

Upload to web UI

You will see digits at the start of all questions

![image](https://github.com/harmonydata/harmony/assets/15210965/fe82d70a-5670-46d4-87d0-002964a9e725)

## Expected Behavior

Digits should be removed

**Comment by woodthom2** [comment]
Also need unit test for this

**Comment by shahid-0** [comment]
I will work on that issue.

**Comment by rman1223** [comment]
This problem is almost close to prompt engineering.
I don't know your model lable status in more detail.
But, prompt engineering is very important to active the model's feature more and need to go over this step.
Thus, I think that it seems to be a good to solve through prompting.
Thank you!

**Comment by evelynnchen-cmu** [comment]
My peers and I will work on this issue.

**Comment by woodthom2** [comment]
Thanks so much!

**Comment by woodthom2** [comment]
This is related to the Harmony PDF challenge https://harmonydata.ac.uk/doxa/
- so we've provided training data to train your own AI to improve Harmony's
PDF extraction. However, you could view it as a separate rule-based
postprocessing step after the PDF extraction. Also sometimes users upload
Excels containing leading and trailing digits and things like that that
need to be stripped out so we could treat this (removing digits) as
something entirely separate. I'm open to discussion about this.
