### ISSUE TITLE
Upgrade Harmony to latest Pydantic 2.8.2 or later

### ISSUE THREAD

**Issue by woodthom2** [harmonydata/harmony#50]
We are using an old version of Pydantic

**Comment by olp-cs** [comment]
Is this issue still available for someone to take on? I can start with it.

A migration guide is available here: https://docs.pydantic.dev/latest/migration/

**Comment by woodthom2** [comment]
Hi yes it is totally available and nobody has looked at it. Thanks so much
for offering, this would be really helpful! When I tried upgrading Pydantic
there are all sorts of errors that come up because of broken backwards
compatibility. While you're looking into it's, if you are able to switch
some of the logging functions from the vanilla Python `print` to proper
logging (I think defined somewhere in the project in `logger.py` or
somewhere that would be fantastic too.

**Comment by olp-cs** [comment]
Thank you for the explanation! I will look into it and check how to fix the compatibility issues. I'll look into logging as well.

**Comment by woodthom2** [comment]
Thanks!

**Comment by woodthom2** [comment]
BTW pydantic would need to be upgraded in both API and Python repos

* https://github.com/harmonydata/harmony
* https://github.com/harmonydata/harmonyapi

**Comment by olp-cs** [comment]
I submitted a pull request to upgrade Pydantic in the current repo. I will look into Harmony API as well.

I couldn't find the logging settings; perhaps it's better to create a separate ticket to address this later.

P.S. By the way, I still have to run the unit tests and integration tests in the API repo.
