### ISSUE TITLE
Add clustering to Harmony Python library

### ISSUE THREAD

**Issue by woodthom2** [harmonydata/harmony#54]
## Description

Can we allow the user to quickly discover clusters between items?
Perhaps an implementation of the t-SNE algorithm

https://cookbook.openai.com/examples/clustering

## Rationale

Sometimes a user might just want to use Harmony for discovery

However if we implement this, the library should not become more bloated. Any new dependencies such as t-SNE could be imported only if the user needs that function.

**Comment by Gabe-ferr** [comment]
Hello, my name is Gabriel and I would love to work on this task.

**Comment by woodthom2** [comment]
Hi Gabriel @Gabe-ferr . Thanks and we're so glad to have you on board and the task is yours! Please feel free to get started. Do you want a discussion before you get started? I'm happy to have a video call with you. Where are you in the world?

Do you want to make a fork, work on that and then make a PR to send your changes back to the full project?

Feel free to message me in [Discord](https://discord.com/invite/harmonydata) - my name is Thomas Wood
